# MySQL version 5.1.50
#   gem install mysql -- --with-mysql-dir=/usr/local/mysql 

development:
    adapter: mysql2
    encoding: utf8
    database: jdr_dev
    username: root
    password:
    host: localhost
    
    
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#development:
#  adapter: sqlite3
#  database: db/development.sqlite3
#  pool: 5
#  timeout: 5000


